version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    description: Setup and run application tests
    executor:
      name: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "WatchsterApplication/Watchster.WebApi/Watchster.WebApi.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore WatchsterApplication/WatchsterApplication.sln
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "WatchsterApplication/Watchster.WebApi/Watchster.WebApi.csproj" }}
      - run:
          name: "Run Application Tests"
          command: dotnet.exe test WatchsterApplication/WatchsterApplication.sln -v n --results-directory:test_coverage --collect:"Code Coverage"
      - run:
          name: "Print Working Directory"
          command: pwd
      - store_artifacts:
          path: C:\Users\circleci\project\test_coverage
  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet build WatchsterApplication/WatchsterApplication.sln
workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test